# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

{{- if (index .Values.metadata.annotations "service.helm.timescale.com/rbac-create") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "timescaledb.fullname" . }}
  labels:
    {{- include "timescaledb.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "timescaledb.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "timescaledb.fullname" . }}
{{- end }}
