# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

apiVersion: v1
name: timescaledb-single
description: 'TimescaleDB HA Deployment.'
version: 0.33.2
icon: https://cdn.iconscout.com/icon/free/png-256/timescaledb-1958407-1651618.png

# appVersion specifies the version of the software, which can vary wildly,
# e.g. TimescaleDB 1.4.1 on PostgreSQL 11 or TimescaleDB 1.5.0 on PostgreSQL 12.
# https://github.com/helm/helm/blob/master/docs/charts.md#the-appversion-field
# To avoid confusion, we will not expose appVersion
# appVersion: 0.0.1
home: https://github.com/timescale/helm-charts
sources:
  - https://github.com/timescale/helm-charts
  - https://github.com/timescale/timescaledb-docker-ha
  - https://github.com/zalando/patroni
maintainers:
  - name: TimescaleDB
    email: support@timescale.com
