# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

apiVersion: v2
name: avalanche
description: A Helm chart run avalanche for benchmarking Prometheus and remote write storage backends.
version: 0.4.0

home: https://github.com/timescale/helm-charts

sources:
  - https://github.com/timescale/helm-charts
  - https://github.com/prometheus-community/avalanche

maintainers:
  - name: timescale
    url: https://www.timescale.com/

keywords:
  - monitoring
  - benchmarking
  - prometheus
