# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

{{- if or .Values.backup.enable .Values.backup.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "timescaledb.fullname" . }}-backup
  labels:
    app: {{ template "timescaledb.fullname" . }}
    chart: {{ template "timescaledb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cluster-name: {{ template "clusterName" . }}
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: {{ template "timescaledb.fullname" . }}
    role: master
    cluster-name: {{ template "clusterName" . }}
...
{{- range .Values.backup.jobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "timescaledb.fullname" $ }}-{{ .name }}
  labels:
    app: {{ template "timescaledb.fullname" $ }}
    chart: {{ template "timescaledb.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    backup-type: {{ .type }}
    cluster-name: {{ template "clusterName" $ }}
spec:
  schedule: {{ quote .schedule }}
  concurrencyPolicy: Forbid
  ttlSecondsAfterFinished: 3600
  jobTemplate:
    metadata:
      labels:
        app: {{ template "timescaledb.fullname" $ }}
        chart: {{ template "timescaledb.chart" $ }}
        release: {{ $.Release.Name }}
        heritage: {{ $.Release.Service }}
        backup-type: {{ .type }}
        cluster-name: {{ template "clusterName" $ }}
    spec:
      template:
        metadata:
          labels:
            app: {{ template "timescaledb.fullname" $ }}
            chart: {{ template "timescaledb.chart" $ }}
            release: {{ $.Release.Name }}
            heritage: {{ $.Release.Service }}
            backup-type: {{ .type }}
            cluster-name: {{ template "clusterName" $ }}
        spec:
          containers:
          - name: {{ template "timescaledb.fullname" $ }}-{{ .type }}
            image: alpine
            command: ["wget"]
            args:
               - -q  # quiet
               - -O- # output to stdout
               - -S  # save headers
               - '--post-data={"type": {{ quote .type }} }'
               - "http://{{ template "timescaledb.fullname" $ }}-backup.{{ $.Release.Namespace }}.svc.cluster.local:8081/backups/"
          restartPolicy: Never
...
{{- end }}
{{ end }}