# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.
#
# This service is only created if Prometheus is enabled.
{{ if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "clusterName" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    component: postgres-exporter
{{ include "timescaledb-helm.labels" . | indent 4 }}
    app.kubernetes.io/component: postgres-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  ports:
    - name: metrics
      port: 9187
  selector:
    app: {{ template "timescaledb.fullname" . }}
{{ end }}
