apiVersion: v2
name: promscale
description: Promscale Connector deployment

version: 14.3.0
appVersion: 0.16.0

home: https://github.com/timescale/promscale
sources:
  - https://github.com/timescale/promscale
  - https://github.com/timescale/helm-charts

maintainers:
  - name: TimescaleDB
    email: support@timescale.com
