metadata:
  # These annotations allow you toggle features in the Helm chart to on/off
  annotations:
    service.helm.timescale.com/backup-enabled: true
    service.helm.timescale.com/backup-method: pgBackRest
    service.helm.timescale.com/network-policy-enabled: False
    service.helm.timescale.com/timescaledb-tune-enabled: False
    service.helm.timescale.com/generate-passwords: True

# This part of the configuration ("spec") has the same definition as the TimescaleDB Custom Resource Definition for
# the Timescale Operator
spec:
  users:
    postgress:
      password:
        valueFrom:
          secretKeyRef:
            name: myverysecret
            key: postgres
    admin:
      password:
        value: notverysecure
      privileges:
        createdb: true
        createrole: true
  databases:
    example:
      encoding: UTF8
      locale: C
  accessNode: ts0
  nodes:
    ts0:
      configuration: default
    ts1:
      configuration: dataNode
      certificate:
        secretKeyRef:
          name: pietje
    ts2:
      configuration: dataNode
  configurations:
    default:
      image: timescaledev/timescaledb-ha:pg11-ts1.6
      replicas: 3
      postgresql:
        version: 11
        parameters:
          work_mem: "16MB"
    dataNode:
      image: timescaledev/timescaledb-ha:pg11-ts1.6
      replicas: 2
      postgresql:
        parameters:
          work_mem: "24MB"
