name: Project Management

on:
  issues:
    types: [opened, reopened]
  release:
    types: [published]
  pull_request_target:
  schedule:
    - cron: '13 2 * * MON' # Run every Monday at 2:13 UTC

jobs:
  assign_issue:
    runs-on: ubuntu-latest
    name: Assign Issue to a Project
    if: github.event_name == 'issues' || github.event_name == 'pull_request_target'
    steps:
    - name: Assign NEW issues/PRs to project O11y Applications
      uses: actions/add-to-project@main
      with:
        project-url: 'https://github.com/orgs/timescale/projects/54'
        # github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
        github-token: ${{ secrets.ORG_PROJECT_PAT }}

  stale-issues-handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          any-of-labels: 'needs-more-info,question'
          stale-pr-label: 'stale'
          exempt-all-milestones: true
          days-before-stale: 30
          days-before-close: 30
          stale-issue-message: |
            This issue went stale because it was not updated in a month. Please consider updating it to improve the quality of the project.
          close-issue-message: 'This issue was closed because it has been stalled for 30 days with no activity.'

  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    name: Label PRs based on files changed
    if: github.event_name == 'pull_request_target'
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
