name: "Test [old]"
on:
- push
- pull_request

env:
  helm-version: v3.10.1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test if Chart.yaml has been touched
        id: single_chart_changed
        run: echo "::set-output name=changes::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} charts/timescaledb-single/Chart.yaml)"

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        if: steps.single_chart_changed.outputs.changes != ''

      - uses: azure/setup-kubectl@v3
        id: install-kubectl
        if: steps.single_chart_changed.outputs.changes != ''

      - uses: azure/setup-helm@v3.3
        id: install-helm
        if: steps.single_chart_changed.outputs.changes != ''
        with:
          version: ${{ env.helm-version }}

      - name: Test all available values files clusters
        run: make test
        if: steps.single_chart_changed.outputs.changes != ''
